version: "3.8"

services:
  #web
  web:
    image: nginx:latest
    container_name: laraxi
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
  #app
  app:
    container_name: laraxii 
    build:
      context: ./php
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  #db
  db:
    container_name: laraxiii
    image: mysql:8
    env_file:
      - ./env/mysql.env
  #composer
  composer:
    build:
      context: ./php
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  #artisan
  artisan:
    build:
      context: ./php
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ["php","var/www/html/artisan"]
  #npm
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
        - ./src:/var/www/html:delegated
