
services:
  #web
  web:
    image: nginx:latest
    container_name: some-web
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - some-network
  #app
  app:
    container_name: some-app
    build:
      context: ./php
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - some-network
  #db
  db:
    container_name: some-db
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    networks:
      - some-network
  #composer
  composer:
    build:
      context: ./php
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - some-network
  #artisan
  artisan:
    build:
      context: ./php
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ["php","artisan"]
    networks:
      - some-network
  #npm
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
        - ./src:/var/www/html:delegated
    networks:
      - some-network
networks:
  some-network:
    driver: bridge


